# Generated by Django 3.1.3 on 2025-01-09 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_remove_task_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('dob', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('short_bio', models.TextField(blank=True, default='This is a short bio.', null=True)),
                ('phone_number', models.CharField(blank=True, default='000-000-0000', max_length=15, null=True)),
                ('education', models.CharField(blank=True, default='No education provided', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
