# Generated by Django 3.1.3 on 2025-01-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20250110_0204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
