# Generated by Django 3.1.3 on 2025-01-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
